import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { MinervaIr } from "@minerva/ir";

export type EmitContext = { outDir: string; repoRoot: string };

const SWIFT_TOOLS = "5.9";

function packageSwift(ir: MinervaIr): string {
  const mod = ir.app.executableModule;
  return `// swift-tools-version: ${SWIFT_TOOLS}
// Generated by @minerva/codegen — do not edit by hand.
import PackageDescription

let package = Package(
    name: "${mod}",
    platforms: [.macOS(.v13)],
    products: [
        .executable(name: "${mod}", targets: ["${mod}"])
    ],
    targets: [
        .executableTarget(
            name: "${mod}",
            path: "Sources/${mod}",
            resources: [.process("Resources")]
        )
    ]
)
`;
}

function readme(ir: MinervaIr, repoRoot: string): string {
  return `# ${ir.app.displayName} (generated macOS host)

Bundle id: \`${ir.app.bundleId}\`

## Build

\`\`\`bash
cd "${path.relative(repoRoot, "generated/macos")}"
cp -R ../../packages/ui-master/build/* Sources/${ir.app.executableModule}/Resources/Web/
swift build -c release
.build/release/${ir.app.executableModule}
\`\`\`

Copy the **master UI** static build into \`Sources/${ir.app.executableModule}/Resources/Web/\` before running (see root \`npm run ui:master:build\`).

## Dev WebView URL

Set environment variable \`MINERVA_DEV_WEB_URL\` to a Vite dev server (e.g. \`http://127.0.0.1:5173\`) to skip bundled assets.
`;
}

function appSwift(ir: MinervaIr): string {
  const mod = ir.app.executableModule;
  const handler = ir.bridge.messageHandler;
  return `import AppKit
import WebKit
import Foundation

@main
enum ${mod}App {
    static func main() {
        let app = NSApplication.shared
        let delegate = AppDelegate()
        app.delegate = delegate
        app.setActivationPolicy(.regular)
        app.activate(ignoringOtherApps: true)
        app.run()
    }
}

final class AppDelegate: NSObject, NSApplicationDelegate {
    var window: NSWindow!
    var host: WebViewHost!

    func applicationDidFinishLaunching(_ notification: Notification) {
        let size = NSSize(width: 1100, height: 780)
        window = NSWindow(
            contentRect: NSRect(origin: .zero, size: size),
            styleMask: [.titled, .closable, .miniaturizable, .resizable],
            backing: .buffered,
            defer: false
        )
        window.title = "${ir.app.displayName}"
        window.center()

        host = WebViewHost(messageHandler: "${handler}")
        let wv = host.webView
        wv.autoresizingMask = [.width, .height]
        window.setContentSize(size)
        wv.frame = NSRect(origin: .zero, size: size)
        window.contentView = wv
        window.makeKeyAndOrderFront(nil)

        host.loadBundledOrDev()
    }

    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool { true }
}
`;
}

function webViewHost(ir: MinervaIr): string {
  const g = ir.bridge.jsGlobal;
  return `import AppKit
import WebKit
import Foundation

/// Loads master UI from bundle \`Resources/Web\` or \`MINERVA_DEV_WEB_URL\`.
final class WebViewHost: NSObject, WKNavigationDelegate, WKScriptMessageHandler {
    let webView: WKWebView
    private let messageHandler: String
    private let bridge: BridgeCoordinator

    init(messageHandler: String) {
        self.messageHandler = messageHandler
        let config = WKWebViewConfiguration()
        config.preferences.setValue(true, forKey: "developerExtrasEnabled")
        let uc = WKUserContentController()
        uc.addUserScript(WebViewHost.injectionScript())
        config.userContentController = uc
        self.webView = WKWebView(frame: .zero, configuration: config)
        self.bridge = BridgeCoordinator(webView: self.webView)
        super.init()
        self.webView.configuration.userContentController.add(self, name: messageHandler)
        self.webView.navigationDelegate = self
        self.webView.setValue(false, forKey: "drawsBackground")
    }

    /// SPM processed resources: \`${ir.app.executableModule}_${ir.app.executableModule}.bundle\` next to the executable.
    /// Avoids \`Bundle.module\`, which some SwiftPM toolchains omit for executable targets (e.g. GitHub Actions).
    private static func resourcesBundle() -> Bundle {
        let main = Bundle.main
        let bundleName = "${ir.app.executableModule}_${ir.app.executableModule}.bundle"
        let dirs: [URL] = [
            main.resourceURL,
            main.executableURL?.deletingLastPathComponent(),
        ].compactMap { $0 }
        for dir in dirs {
            let url = dir.appendingPathComponent(bundleName)
            if let b = Bundle(url: url),
               b.url(forResource: "index", withExtension: "html", subdirectory: "Web") != nil {
                return b
            }
        }
        return main
    }

    func loadBundledOrDev() {
        if let dev = ProcessInfo.processInfo.environment["MINERVA_DEV_WEB_URL"],
           let u = URL(string: dev) {
            webView.load(URLRequest(url: u))
            return
        }
        let module = Self.resourcesBundle()
        if let idx = module.url(forResource: "index", withExtension: "html", subdirectory: "Web") {
            webView.loadFileURL(idx, allowingReadAccessTo: idx.deletingLastPathComponent())
            return
        }
        let html = """
        <!DOCTYPE html><meta charset="utf-8">
        <title>${ir.app.displayName}</title>
        <body style="font:14px system-ui;padding:2rem;background:#111;color:#eee">
        <p>Missing <code>Resources/Web</code>. Run <code>npm run ui:master:build</code> and copy <code>packages/ui-master/build/*</code> into
        <code>Sources/${ir.app.executableModule}/Resources/Web/</code>, then rebuild.</p>
        </body>
        """
        webView.loadHTMLString(html, baseURL: nil)
    }

    func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {
        guard message.name == messageHandler,
              let body = message.body as? [String: Any] else { return }
        bridge.handle(message: body)
    }

    private static func injectionScript() -> WKUserScript {
        let source = """
        (function() {
          window.${g} = window.${g} || {};
          window.__minervaPending = window.__minervaPending || {};
          window.__minervaDeliver = function(id, payload) {
            var p = window.__minervaPending[id];
            if (!p) return;
            delete window.__minervaPending[id];
            if (payload && payload.ok === false) {
              p.reject(new Error(payload.error || 'Native error'));
            } else {
              p.resolve(payload && Object.prototype.hasOwnProperty.call(payload, 'result') ? payload.result : payload);
            }
          };
          window.${g}.invoke = function(cmd, payload) {
            return new Promise(function(resolve, reject) {
              var id = 'm' + Math.random().toString(36).slice(2);
              window.__minervaPending[id] = { resolve: resolve, reject: reject };
              window.webkit.messageHandlers.${ir.bridge.messageHandler}.postMessage({ op: cmd, id: id, payload: payload || {} });
            });
          };
        })();
        """
        return WKUserScript(source: source, injectionTime: .atDocumentStart, forMainFrameOnly: false)
    }
}
`;
}

function bridgeCoordinator(): string {
  return `import WebKit
import Foundation

final class BridgeCoordinator {
    private weak var webView: WKWebView?
    private let searx = SearxService()
    private let settings = SettingsStore()
    private let llm = LlmService()

    init(webView: WKWebView) {
        self.webView = webView
    }

    func handle(message: [String: Any]) {
        guard let op = message["op"] as? String,
              let id = message["id"] as? String else { return }
        let payload = message["payload"] as? [String: Any] ?? [:]
        Task {
            do {
                let result: Any = try await dispatch(op: op, payload: payload)
                await deliver(id: id, body: ["ok": true, "result": result])
            } catch {
                await deliver(id: id, body: ["ok": false, "error": error.localizedDescription])
            }
        }
    }

    private func dispatch(op: String, payload: [String: Any]) async throws -> Any {
        switch op {
        case "searxSearch":
            let q = payload["query"] as? String ?? ""
            let cat = payload["categories"] as? String ?? "general"
            let json = try await searx.search(query: q, categories: cat)
            return json
        case "loadSettings":
            return settings.load()
        case "saveSettings":
            let json = payload["json"] as? String ?? "{}"
            try settings.save(json: json)
            return true
        case "llmChat":
            let body = payload["body"] as? String ?? "{}"
            let text = try await llm.chat(jsonBody: body)
            return text
        case "searxStatus":
            let s = settings.load()
            return try await searx.probeStatus(settingsJson: s)
        default:
            throw NSError(domain: "Minerva", code: 1, userInfo: [NSLocalizedDescriptionKey: "Unknown op: \\(op)"])
        }
    }

    @MainActor
    private func deliver(id: String, body: [String: Any]) {
        guard let wv = webView else { return }
        guard let data = try? JSONSerialization.data(withJSONObject: body),
              let jsonStr = String(data: data, encoding: .utf8) else { return }
        let script = "window.__minervaDeliver('\\(id)', \\(jsonStr))"
        wv.evaluateJavaScript(script, completionHandler: nil)
    }
}
`;
}

function searxService(): string {
  return `import Foundation

struct AppSettingsDTO: Codable {
    var searxBaseUrl: String
    var llamaHost: String
    var llamaPort: Int
}

enum SearxServiceError: Error {
    case badURL
    case http(Int)
    case transport(Error)
}

final class SearxService {
    private let session: URLSession = {
        let c = URLSessionConfiguration.ephemeral
        c.timeoutIntervalForRequest = 60
        return URLSession(configuration: c)
    }()

    func decodedSettings(_ json: String) throws -> AppSettingsDTO {
        let data = Data(json.utf8)
        struct Wrap: Codable { let searxBaseUrl: String?; let llamaHost: String?; let llamaPort: Int? }
        let w = try JSONDecoder().decode(Wrap.self, from: data)
        return AppSettingsDTO(
            searxBaseUrl: w.searxBaseUrl ?? "http://127.0.0.1:18080",
            llamaHost: w.llamaHost ?? "127.0.0.1",
            llamaPort: w.llamaPort ?? 8081
        )
    }

    func search(query: String, categories: String) async throws -> String {
        let raw = loadSettingsJson()
        let s = try decodedSettings(raw)
        var base = s.searxBaseUrl.trimmingCharacters(in: .whitespacesAndNewlines)
        while base.hasSuffix("/") { base.removeLast() }
        guard var comp = URLComponents(string: base + "/search") else { throw SearxServiceError.badURL }
        comp.queryItems = [
            URLQueryItem(name: "format", value: "json"),
            URLQueryItem(name: "q", value: query),
            URLQueryItem(name: "categories", value: categories)
        ]
        guard let url = comp.url else { throw SearxServiceError.badURL }
        var req = URLRequest(url: url)
        req.setValue(base + "/", forHTTPHeaderField: "Referer")
        let (data, res) = try await session.data(for: req)
        if let http = res as? HTTPURLResponse, http.statusCode != 200 {
            throw SearxServiceError.http(http.statusCode)
        }
        return String(data: data, encoding: .utf8) ?? ""
    }

    func probeStatus(settingsJson: String) async throws -> [String: Any] {
        let s = try decodedSettings(settingsJson)
        let base = s.searxBaseUrl.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let url = URL(string: base + "/search?format=json&q=minerva_ping&categories=general") else {
            throw SearxServiceError.badURL
        }
        var req = URLRequest(url: url)
        req.setValue(base + "/", forHTTPHeaderField: "Referer")
        do {
            let (_, res) = try await session.data(for: req)
            let code = (res as? HTTPURLResponse)?.statusCode ?? 0
            return ["reachable": code == 200, "statusCode": code, "baseUrl": base]
        } catch {
            return ["reachable": false, "error": String(describing: error), "baseUrl": base]
        }
    }

    private func loadSettingsJson() -> String {
        SettingsStore().load()
    }
}
`;
}

function settingsStore(): string {
  return `import Foundation

final class SettingsStore {
    private var fileURL: URL {
        let dir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let sub = dir.appendingPathComponent("Minerva", isDirectory: true)
        try? FileManager.default.createDirectory(at: sub, withIntermediateDirectories: true)
        return sub.appendingPathComponent("settings.json")
    }

    func load() -> String {
        (try? String(contentsOf: fileURL, encoding: .utf8))
            ?? defaultSettings()
    }

    func save(json: String) throws {
        try json.write(to: fileURL, atomically: true, encoding: .utf8)
    }

    private func defaultSettings() -> String {
        """
        {"searxBaseUrl":"http://127.0.0.1:18080","llamaHost":"127.0.0.1","llamaPort":8081,"llmContextTokens":32768}
        """
    }
}
`;
}

function llmService(): string {
  return `import Foundation

final class LlmService {
    private let session: URLSession = {
        let c = URLSessionConfiguration.ephemeral
        c.timeoutIntervalForRequest = 120
        return URLSession(configuration: c)
    }()

    /// jsonBody is the POST body for /v1/chat/completions
    func chat(jsonBody: String) async throws -> String {
        let store = SettingsStore()
        let sjson = store.load()
        let data = Data(sjson.utf8)
        struct S: Codable { let llamaHost: String?; let llamaPort: Int? }
        let s = try JSONDecoder().decode(S.self, from: data)
        let host = s.llamaHost ?? "127.0.0.1"
        let port = s.llamaPort ?? 8081
        guard let url = URL(string: "http://\\(host):\\(port)/v1/chat/completions") else {
            throw URLError(.badURL)
        }
        var req = URLRequest(url: url)
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = Data(jsonBody.utf8)
        let (respData, res) = try await session.data(for: req)
        if let http = res as? HTTPURLResponse, http.statusCode != 200 {
            let t = String(data: respData, encoding: .utf8) ?? ""
            throw NSError(domain: "Minerva", code: http.statusCode, userInfo: [NSLocalizedDescriptionKey: t])
        }
        return String(data: respData, encoding: .utf8) ?? ""
    }
}
`;
}

export async function emitMacos(ir: MinervaIr, ctx: EmitContext): Promise<void> {
  const mod = ir.app.executableModule;
  const base = path.join(ctx.outDir, `Sources/${mod}`);
  const res = path.join(base, "Resources/Web");
  await mkdir(res, { recursive: true });
  await writeFile(path.join(ctx.outDir, "Package.swift"), packageSwift(ir));
  await writeFile(path.join(ctx.outDir, "README.md"), readme(ir, ctx.repoRoot));
  await writeFile(path.join(base, `${mod}App.swift`), appSwift(ir));
  await writeFile(path.join(base, "WebViewHost.swift"), webViewHost(ir));
  await writeFile(path.join(base, "BridgeCoordinator.swift"), bridgeCoordinator());
  await writeFile(path.join(base, "SearxService.swift"), searxService());
  await writeFile(path.join(base, "SettingsStore.swift"), settingsStore());
  await writeFile(path.join(base, "LlmService.swift"), llmService());
  await writeFile(
    path.join(res, ".gitkeep"),
    "# Copy ui-master build output here after npm run ui:master:build\n",
  );
}
